export const fetchData = async () => {
  return [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      phone: "123-456-7890",
      address: { city: "New York" },
      company: { name: "Acme Corp" },
      medicalIssue: "Fever",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "987-654-3210",
      address: { city: "Los Angeles" },
      company: { name: "Health Inc" },
      medicalIssue: "Headache",
    },
    {
      id: 3,
      name: "Robert Brown",
      email: "robert@example.com",
      phone: "555-123-4567",
      address: { city: "Chicago" },
      company: { name: "Wellness Co" },
      medicalIssue: "Cough",
    },
    {
      id: 4,
      name: "Emily Davis",
      email: "emily@example.com",
      phone: "444-555-6666",
      address: { city: "Houston" },
      company: { name: "Medicare LLC" },
      medicalIssue: "Cold",
    },
    {
      id: 5,
      name: "Michael Johnson",
      email: "michael@example.com",
      phone: "111-222-3333",
      address: { city: "Phoenix" },
      company: { name: "Care Solutions" },
      medicalIssue: "Back Pain",
    },
    {
      id: 6,
      name: "Olivia Martinez",
      email: "olivia@example.com",
      phone: "999-888-7777",
      address: { city: "Philadelphia" },
      company: { name: "LifeHealth" },
      medicalIssue: "Allergy",
    },
    {
      id: 7,
      name: "William Taylor",
      email: "william@example.com",
      phone: "333-444-5555",
      address: { city: "San Antonio" },
      company: { name: "CureFast" },
      medicalIssue: "Diabetes",
    },
    {
      id: 8,
      name: "Sophia Anderson",
      email: "sophia@example.com",
      phone: "222-333-4444",
      address: { city: "San Diego" },
      company: { name: "MedTech" },
      medicalIssue: "Flu",
    },
    {
      id: 9,
      name: "James Thomas",
      email: "james@example.com",
      phone: "777-666-5555",
      address: { city: "Dallas" },
      company: { name: "HealWell" },
      medicalIssue: "High Blood Pressure",
    },
    {
      id: 10,
      name: "Isabella Wilson",
      email: "isabella@example.com",
      phone: "888-777-6666",
      address: { city: "San Jose" },
      company: { name: "DocCare" },
      medicalIssue: "Asthma",
    },
  ];
};
